Add 309: Test flexdashboard tab and page management with {bslib}
rstudio/shinycoreci pull request #155
Opened 2023-03-20 15:05 UTC by gadenbuie

Adds an app for testing tab and page management that rely on Bootstraps Tab plugin, as managed by bslib, over Bootstrap version 3, 4 and 5.

* This currently fails, as expected, for Bootstrap 5 with the CRAN version of flexdashboard (0.6.1) and latest bslib. 
* It is, however, fixed by https://github.com/rstudio/bslib/pull/501

Fixes #154

2023-03-20 16:29 UTC, cpsievert commented on inst/apps/309-flexdashboard-tabs-navs/index.Rmd
> +
Maybe have some preface explaining what this test app is doing

2023-03-20 17:56 UTC, cpsievert commented on inst/apps/309-flexdashboard-tabs-navs/tests/testthat/test-shinytest2.R
> +  expect_false(app$get_js(is_test_element_visible(!!test_id)))
Since these tests are essentially purely client-side, it'd probably faster/better to use `{shinyjster}` instead of `{shinytest2}`, for example:

https://github.com/rstudio/shinycoreci/blob/fb236b8ac48b236479382215250e4d15b20afd0d/inst/apps/187-navbar-collapse/app.R#L10-L45

2023-03-20 18:05 UTC, schloerke requested changes

2023-03-21 15:43 UTC, gadenbuie commented on inst/apps/309-flexdashboard-tabs-navs/tests/testthat/test-shinytest2.R
> +  expect_false(app$get_js(is_test_element_visible(!!test_id)))
@schloerke Is shinyjster designed to facilitate running and testing R Markdown Shiny apps using `runtime: shiny`? (I couldn't find anything in the docs.)

It seems like the biggest advantage of using shinyjster would be to test in Chrome, Edge, and Firefox. From looking at the logs of previous runs, though, and unless I'm misunderstanding them, I would expect switching to shinyjster to increase the test time for these tests. Right now, they take ~7 seconds locally on my M1 for all three Bootstrap variants. With shinyjster we'd be adding two more browsers into the matrix.

2023-03-21 16:45 UTC, schloerke commented on inst/apps/309-flexdashboard-tabs-navs/tests/testthat/test-shinytest2.R
> +  expect_false(app$get_js(is_test_element_visible(!!test_id)))
`{shinyjster}` can run inside Rmd docs. Ex: https://github.com/rstudio/shinycoreci/blob/fb236b8ac48b236479382215250e4d15b20afd0d/inst/apps/185-report-theme/index.Rmd#L135-L174

Yes, it's reasonable that the time would be increased, but it is not by a large factor. I'd be comfortable using shinyjster.

2023-03-23 14:33 UTC, gadenbuie commented on inst/apps/309-flexdashboard-tabs-navs/tests/testthat/test-shinytest2.R
> +    }
You make some great points! There's always a tradeoff between maintaining the code that runs the tests and the usability of the tests themselves.

> The error message won't say that  `app$get_js(is_test_element_visible("Box 2-1"))` is not TRUE?

Yeah that's true, and I should have said that the _line number_ or _the failing line of code_ is itself helpful. The complete error message (currently) is

```
Failure (test-shinytest2.R:113): 309-flexdashboard-tabs-navs with BS5
app$get_js(is_test_element_visible("Box 2-1")) is not FALSE

`actual`:   TRUE 
`expected`: FALSE
Backtrace:
 1. expect_test_element_hidden(app, "Box 2-1")
      at test-shinytest2.R:113:4
 2. testthat::expect_false(app$get_js(is_test_element_visible(!!test_id)))
      at test-shinytest2.R:17:2
```

That's not the greatest error message. But it does have the advantage of telling me exactly which line to look at: 113.

```r
# other lines that get the app into the failed state...
expect_test_element_hidden(app, "Box 2-1") # line 113
```

When the test fails I'll have forgotten almost everything about this test or what the app is supposed to be doing. (Or someone else will have never seen this test before.) The idea is to make it as easy as possible for the person doing the debugging to get into the failed state so they can start working with the app.

In the current situation, there's a small amount of cognitive overhead with the helper functions, but they're super small and basically each give one line of code a better name. Then there's the for loop over `bs_version`, which is at least slightly annoying. But after setting `bs_version <- 5`, the person doing the debugging can just run everything up to line 113 to get the app into the bad state.

In contrast, with the helper function, the failing test doesn't give you a "stop at this line" hint. To debug the failing test, you'd need to set up break points or add `browser()` calls. Not untenable, but if you're also going to be instrumenting package code it starts to feel like extra overhead.

With the wrapper function you suggested (something similar named `expect_only_page_visible()`) the error message is

```
Failure (test-shinytest2.R:117): 309-flexdashboard-tabs-navs with BS5
app$get_js(is_test_element_visible("Box 2-1")) is not FALSE

`actual`:   TRUE 
`expected`: FALSE
Backtrace:
 1. expect_only_page_visible(app, 3)
      at test-shinytest2.R:117:4
 2. expect_test_element_hidden(app, test_id)
      at test-shinytest2.R:49:6
 3. testthat::expect_false(app$get_js(is_test_element_visible(!!test_id)))
      at test-shinytest2.R:17:2
```

Line 117 gives me some code to run, but then I have to get into the guts of `expect_only_page_visible()` to find the specific expectation that's failing. And because of the for loops I also can't just put a break point on line 49 or I'll hit every test for hidden elements on my way to the one I want to see.

> In my approach, the App and `expect_visible()` have entered into a shape contract where the tests expect certain shape from the App.

Yeah this is a good point and probably also where my hesitation comes from. I'm not sure I want a shape contract. I certainly didn't write the app with the intention of creating one. I'm actually even on the fence about whether or not we should be testing the visibility of the boxes in the first place. Mostly I added them so that there's something visually different that clearly indicates which page you're on. And then once they're there I included them in the tests because they were there. If I felt the structure were super important to the app, I'd be all in favor of a larger expectation wrapper that solidifies that contract.

2023-03-23 14:43 UTC, schloerke commented on inst/apps/309-flexdashboard-tabs-navs/tests/testthat/test-shinytest2.R
> +    }
We both (unbudgingly) agree our approach is better. 😜 Both are solid approaches

I'll resolve the convo and have you keep your code as is.

--------

We can re address shinycoreci's testing philosophy for other apps with _very_ abstracted tests. 😂😭

2023-05-02 18:35 UTC, schloerke commented
- [ ] https://github.com/rstudio/bslib/pull/501 is merged

2023-05-08 22:47 UTC, cpsievert commented
> This currently fails, as expected, for Bootstrap 5 with the CRAN version of flexdashboard (0.6.1) and latest bslib.

Does this really matter though since shinycoreci tests against the github version of flexdashboard (which has [a fix](https://github.com/rstudio/flexdashboard/commit/a65e8c43164f3d68723e53d39120d2bffcf60e71) for this)? All the tests seem to be passing so this seems ok to merge as is?

2023-05-09 15:13 UTC, cpsievert approved these changes

2023-05-09 17:46 UTC, merged